Repository amyhuang95/LAN-Sharing-Service, pull requests merged in 2025-02, with the labels that each got.

#9 [iter1]: skeleton and backbone
  .gitignore
  .lanshare.conf
  README.md
  __init__.py
  create.py
  lanshare/config/settings.py
  lanshare/core/discovery.py
  lanshare/core/types.py
  lanshare/core/udp_discovery.py
  lanshare/ui/debug_view.py
  lanshare/ui/message_view.py
  lanshare/ui/session.py
  lanshare/ui/user_list_view.py
  requirements.txt
Labels: documentation, feature

#11 [fix]: update timestamp of received message to local time
  lanshare/core/udp_discovery.py
Labels: bug

#15 [doc]: add docstring, detailed function descriptions, and comments
  create.py
  lanshare/config/settings.py
Labels: documentation, asap

#16 [doc]: add docstring, detailed function descriptions, and comments
  lanshare/core/discovery.py
  lanshare/core/types.py
  lanshare/core/udp_discovery.py
Labels: documentation, asap
